// productivity-suite/app/fragments/todos/src/components/headless/HeadlessLink/HeadlessLink.tsx
import type { DOMAttributes } from 'react'
import { getBus } from "piercing-library";

import type { HeadlessLinkProps } from './type'

export const HeadlessLink = ({
  children,
  href,
  isExternal = false,
  className
}: HeadlessLinkProps) => {
  const onClick: DOMAttributes<HTMLAnchorElement>['onClick'] = (e) => {
    if (!isExternal && !e.altKey && !e.shiftKey && !e.ctrlKey && !e.metaKey) {
      e.preventDefault()
      getBus().dispatch("href", href);
    }
  }

  return (
    <a
      href={href}
      onClick={onClick}
      {...(isExternal ? {
        target: '_blank',
        rel: 'noopener',
      } : {})}
      className={className}
    >
      {children}
    </a>
  )
}

// productivity-suite/app/fragments/login/src/components/headless/HeadlessLink/HeadlessLink.tsx
import { getBus } from "piercing-library";
import { component$, Slot } from '@builder.io/qwik';

import type { HeadlessLinkProps } from './type'

export default component$(({
  href,
  isExternal = false,
  className
}: HeadlessLinkProps) => {
  return (
    <a
      href={href}
      preventdefault:click={!isExternal}
      onClick$={() => {
        getBus().dispatch("href", href);
      }}
      {...(isExternal ? {
        target: '_blank',
        rel: 'noopener',
      } : {})}
      className={className}
    >
      <Slot />
    </a>
  )
})
