// productivity-suite/app/legacy-app/src/components/pages/Sample.tsx
import { DOMAttributes } from 'react'
import { getBus } from 'piercing-library'

export function Sample() {
  const onClickLink: DOMAttributes<HTMLAnchorElement>['onClick'] = (e) => {
    e.preventDefault()
    getBus().dispatch("href", '/login');
  }

  return (
    <div style={{
      padding: '100px',
      background: '#ffcccc'
    }}>
      <p>サンプルページ</p>
      <a href='/login' onClick={onClickLink}>Login Link</a>
      <piercing-fragment-outlet fragment-id="login" />
    </div>
  );
}

// productivity-suite/app/legacy-app-nuxt-v2/pages/sample/index.vue
<template>
  <div :style="{
    padding: '100px',
    background: '#ffcccc'
  }">
    <p>サンプルページ</p>
    <HeadlessLink href='/login'>Login Link</HeadlessLink>
  </div>
</template>

<script lang="ts">
import Vue from 'vue'
import HeadlessLink from '@/components/headless/HeadlessLink/index.vue'

export default Vue.extend({
  name: 'IndexPage',
  components: {
    HeadlessLink
  },
})
</script>
