// productivity-suite/app/fragments/login/src/components/headless/HeadlessLink/HeadlessLink.tsx
import { getBus } from "piercing-library";
import { component$, Slot } from '@builder.io/qwik';

import type { HeadlessLinkProps } from './type'

export default component$(({
  href,
  isExternal = false,
  className
}: HeadlessLinkProps) => {
  return (
    <a
      href={href}
      preventdefault:click={!isExternal}
      onClick$={() => {
        getBus().dispatch("href", href);
      }}
      {...(isExternal ? {
        target: '_blank',
        rel: 'noopener',
      } : {})}
      className={className}
    >
      <Slot />
    </a>
  )
})

// productivity-suite/app/legacy-app-nuxt-v2/components/headless/HeadlessLink/index.vue


<template>
  <a
    :href="href"
    :target="isExternal ? '_blank' : undefined"
    :rel="isExternal ? 'noopener' : undefined"
    @click="onClickLink"
  >
    <slot />
  </a>
</template>

<script lang="ts">
import Vue from 'vue'
import { getBus } from "piercing-library";

export default Vue.extend({
  name: 'IndexPage',
  props: {
    href: {
      type: String,
      required: true
    },
    isExternal: {
      type: Boolean,
      default: false
    },
    className: {
      type: String,
      required: false
    }
  },
  methods: {
    onClickLink(e: any) {
      e.preventDefault()
      getBus().dispatch("href", this.href);
    }
  }
})
</script>
